#!/bin/sh

PATH="tools/ops-docker:${PATH}"

suffix="$1"

if [ "${suffix}" = 'full' ]; then
  suffix=''
elif [ ! -z "${suffix}" ]; then
  suffix="-${suffix}"
fi

ops-docker -c "conf/docker${suffix}.cfg" rollback
